version: 2.1

jobs:
  build:
    docker:
      -image: cimg/python:3.11
    steps:
      -checkout
      -run: python main.py
  test:
    docker:
      -image: cimg/python:3.11
    steps:
      -checkout
      -run: python test.py
  deploy:
    docker:
       - image: cimg/python:3.11
    steps:
       - run: echo "practical done"

workFlows:
  build_and_test _deploy:
    jobs:
      -build
      -test:
         reqires:
            -build
      -delploy:
          requires:
             -test
          filters:
             branches:
                only: main
                